services:
  db:
    image: mysql:8.0
    container_name: notefy_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notefy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    depends_on:
      - db
    env_file:
      - .env

  studio:
    image: node:18-alpine
    container_name: prisma_studio
    working_dir: /app
    command: [ "npx", "prisma", "studio" ]
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
